spring:
  data:
    mongodb:
      username: jonnie254
      password: jonnie254
      host: localhost
      port: 27017
      database: authenticationdb
      authentication-database: admin
  mail:
    host: localhost
    port: 1025
    username: maildev
    password: maildev
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

application:
  mailing:
    frontend:
      activationUrl: http://localhost:4200/activate-account

  security:
    jwt:
      expiration-time: ${APPLICATION_SECURITY_JWT_EXPIRATION_TIME}
      secret-key: ${APPLICATION_SECURITY_JWT_SECRET_KEY}
  cloudinary:
    cloud-name: ${APPLICATION_SECURITY_CLOUDINARY_CLOUD_NAME}
    api-key: ${APPLICATION_SECURITY_CLOUDINARY_API_KEY}
    api-secret: ${APPLICATION_SECURITY_CLOUDINARY_API_SECRET}
    folder: ${APPLICATION_SECURITY_CLOUDINARY_FOLDER}

server:
  port: 8010