spring:
  datasource:
    url: jdbc:postgresql://localhost:5442/enrollmentdb
    username: jonnie254
    password: jonnie254
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8030

application:
  config:
    authentication-url: http://localhost:8222/api/v1/users
    course-url: http://localhost:8222/api/v1/courses
    payment-url: http://localhost:8222/api/v1/payments