spring:
  data:
    mongodb:
      username: jonnie254
      password: jonnie254
      host: localhost
      port: 27017
      database: notificationdb
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup, cartGroup
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: cartConfirmation:com.jonnie.elearning.kafka.cart.CartConfirmation, paymentConfirmation:com.jonnie.elearning.kafka.Payment.PaymentConfirmation
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    host: localhost
    port: 1025
    username: maildev
    password: maildev
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
server:
  port: 8050
