spring:
  data:
    mongodb:
      username: jonnie254
      password: jonnie254
      host: localhost
      port: 27017
      database: paymentdb
      authentication-database: admin

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: enrollmentConfirmation:com.jonnie.elearning.kafka.enrollment.EnrollmentConfirmation, paymentConfirmation:com.jonnie.elearning.kafka.notification.PaymentNotificationRequest, cartNotification:com.jonnie.elearning.kafka.cart.CartNotification


server:
  port: 8040
