spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
   name: course-service
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
