spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: authentication-service
application:
  security:
    jwt:
      expiration-time: 86400000
      secret-key: yugioewih3qdqwonknflapw0hoiufheoiwqfsncnciienckdsnvoiewifjiewnflvdviuhr89448392952







