spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: payment-service

application:
  config:
    course-url: http://localhost:8222/api/v1/courses
  paypal:
    client-Id: ${PAYPAL_CLIENT_ID}
    client-Secret: ${PAYPAL_CLIENT_SECRET}
    mode: ${PAYPAL_MODE}
  paypal-url:
    success-url: http://localhost:8222/api/v1/payments/success
    cancel-url: http://localhost:8222/api/v1/payments/cancel
