spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
   name: enrollment-service
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
         spring.json.type.mapping: cartConfirmation:com.jonnie.elearning.kafka.cart.CartConfirmation, chatCreationRequest:com.jonnie.elearning.kafka.chat.ChatCreationRequest
    consumer:
      bootstrap-servers: localhost:9092
      group-id: enrollment-group, cart-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        #point to the class that will be used to deserialize the message
        spring.json.type.mapping: enrollmentConfirmation:com.jonnie.elearning.kafka.enrollment.EnrollmentConfirmation, cartNotification:com.jonnie.elearning.kafka.cart.CartNotification
      auto-offset-reset: earliest



