spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway-service

application:
  security:
    jwt:
      secret-key: yugioewih3qdqwonknflapw0hoiufheoiwqfsncnciienckdsnvoiewifjiewnflvdviuhr89448392952